name: "OCA Maintainer Tools Action (Experiment)"
description: "Run maintainer tools from github actions"
author: "Iván Todorovich"
inputs:
  addons-dir:
    description: "Input to use"
    default: "."
    required: false
  org-name:
    description: "Input to use"
    required: true
  repo-name:
    description: "Input to use"
    required: true
  branch-name:
    description: "Input to use"
    required: true
  commit:
    description: "Should commit?"
    required: false
    default: "true"
runs:
  using: "docker"
  image: "Dockerfile"
