name: build

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ github.repository }}:master
          labels: org.opencontainers.image.source=${{ github.event.repository.html_url }}
          push: true
      -
        name: Release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          labels: org.opencontainers.image.source=${{ github.event.repository.html_url }}
          push: true
